### ISSUE TITLE
[Bug]: Not able to run locally using the given steps

### ISSUE THREAD

**Issue by vigneshs-dev** [nz-m/SocialEcho#59]
### Contact Details

vigneshkavery97@gmail.com

### Bug Description

Most of the packages were deprecated, when I use the "npm install" command on both client and server location. Can you please update the steps to run for the latest node framework. 

### Environment

Windows

### Reproduction Steps

cd server
npm install

cd ../client
npm install

### Browsers

Firefox, Microsoft Edge

### Relevant Log Output

```shell
npm start command output for client:

Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:79:19)
    at Object.createHash (node:crypto:139:10)
    at module.exports (C:\Users\Vignesh\Vicky\MERN\SocialEcho\client\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\Vignesh\Vicky\MERN\SocialEcho\client\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\Vignesh\Vicky\MERN\SocialEcho\client\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\Vignesh\Vicky\MERN\SocialEcho\client\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\Vignesh\Vicky\MERN\SocialEcho\client\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\Vignesh\Vicky\MERN\SocialEcho\client\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\Vignesh\Vicky\MERN\SocialEcho\client\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\Users\Vignesh\Vicky\MERN\SocialEcho\client\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
C:\Users\Vignesh\Vicky\MERN\SocialEcho\client\node_modules\react-scripts\scripts\start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:79:19)
    at Object.createHash (node:crypto:139:10)
    at module.exports (C:\Users\Vignesh\Vicky\MERN\SocialEcho\client\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\Vignesh\Vicky\MERN\SocialEcho\client\node_modules\webpack\lib\NormalModule.js:417:16)
    at C:\Users\Vignesh\Vicky\MERN\SocialEcho\client\node_modules\webpack\lib\NormalModule.js:452:10
    at C:\Users\Vignesh\Vicky\MERN\SocialEcho\client\node_modules\webpack\lib\NormalModule.js:323:13
    at C:\Users\Vignesh\Vicky\MERN\SocialEcho\client\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at C:\Users\Vignesh\Vicky\MERN\SocialEcho\client\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (C:\Users\Vignesh\Vicky\MERN\SocialEcho\client\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at C:\Users\Vignesh\Vicky\MERN\SocialEcho\client\node_modules\babel-loader\lib\index.js:59:103 {
  opensslErrorStack: [
    'error:03000086:digital envelope routines::initialization error',
    'error:0308010C:digital envelope routines::unsupported'
  ],
  library: 'digital envelope routines',
  reason: 'unsupported',
Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:79:19)
    at Object.createHash (node:crypto:139:10)
    at module.exports (C:\Users\Vignesh\Vicky\MERN\SocialEcho\client\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\Vignesh\Vicky\MERN\SocialEcho\client\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\Vignesh\Vicky\MERN\SocialEcho\client\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\Vignesh\Vicky\MERN\SocialEcho\client\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\Vignesh\Vicky\MERN\SocialEcho\client\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\Vignesh\Vicky\MERN\SocialEcho\client\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\Vignesh\Vicky\MERN\SocialEcho\client\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\Users\Vignesh\Vicky\MERN\SocialEcho\client\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
C:\Users\Vignesh\Vicky\MERN\SocialEcho\client\node_modules\react-scripts\scripts\start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:79:19)
    at Object.createHash (node:crypto:139:10)
    at module.exports (C:\Users\Vignesh\Vicky\MERN\SocialEcho\client\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\Vignesh\Vicky\MERN\SocialEcho\client\node_modules\webpack\lib\NormalModule.js:417:16)
    at C:\Users\Vignesh\Vicky\MERN\SocialEcho\client\node_modules\webpack\lib\NormalModule.js:452:10
    at C:\Users\Vignesh\Vicky\MERN\SocialEcho\client\node_modules\webpack\lib\NormalModule.js:323:13
    at C:\Users\Vignesh\Vicky\MERN\SocialEcho\client\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at C:\Users\Vignesh\Vicky\MERN\SocialEcho\client\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (C:\Users\Vignesh\Vicky\MERN\SocialEcho\client\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at C:\Users\Vignesh\Vicky\MERN\SocialEcho\client\node_modules\babel-loader\lib\index.js:59:103 {
  opensslErrorStack: [
    'error:03000086:digital envelope routines::initialization error',
    'error:0308010C:digital envelope routines::unsupported'
  ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v20.16.0





npm start command for server:

npm start

> socialecho@1.0.0 start
> nodemon app.js

[nodemon] 2.0.22
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node app.js`
C:\Users\Vignesh\Vicky\MERN\SocialEcho\server\node_modules\passport-jwt\lib\strategy.js:45
        throw new TypeError('JwtStrategy requires a secret or key');
        ^

TypeError: JwtStrategy requires a secret or key
    at new JwtStrategy (C:\Users\Vignesh\Vicky\MERN\SocialEcho\server\node_modules\passport-jwt\lib\strategy.js:45:15)
    at Object.<anonymous> (C:\Users\Vignesh\Vicky\MERN\SocialEcho\server\config\passport.js:13:3)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)        
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10) 
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (C:\Users\Vignesh\Vicky\MERN\SocialEcho\server\app.js:49:1)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)        

Node.js v20.16.0
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by srujanGowda08** [comment]
I have reviewed the bug description and identified the root causes for both the client and server errors. I am confident that I can resolve the problems by updating the environment configurations and addressing the dependency issues.

Please assign this task to me, and I will ensure it is resolved promptly.

**Comment by Siddhesh-2005** [comment]
I've opened a PR that improves the local setup documentation and configuration instructions.

PR: #77 

Please let me know if any additional changes are needed.
